// Original procedural score. No official recording or melody is bundled.
export class Audio {
 constructor(){this.enabled=true;this.ctx=null;this.next=0;this.note=0;this.level=0;this.original=null;}
 async unlock(){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=.16;this.master.connect(this.ctx.destination);}if(this.ctx.state==='suspended')await this.ctx.resume();}
 toggle(){this.enabled=!this.enabled;if(this.master)this.master.gain.setTargetAtTime(this.enabled?.16:0,this.ctx.currentTime,.1);if(this.original)this.original.muted=!this.enabled;return this.enabled;}
 tone(freq,duration=.2,type='sine',vol=.25,at=this.ctx?.currentTime||0){if(!this.ctx)return;const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(vol,at+.012);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(gain);gain.connect(this.master);osc.start(at);osc.stop(at+duration+.02);}
 effect(name){if(!this.ctx||!this.enabled)return;const t=this.ctx.currentTime;if(name==='win')for(const [i,f]of [261.63,329.63,392,523.25].entries())this.tone(f,.4,'sine',.32,t+i*.12);else if(name==='lose'||name==='glass'||name==='crack'){this.tone(73,.5,'sawtooth',.24);this.tone(59,.7,'triangle',.18,t+.08);}else if(name==='signal')this.tone(660,.14,'sine',.4);else if(name==='jump')this.tone(220,.1,'sine',.13);else if(name==='score'||name==='pull')this.tone(440,.18,'triangle',.2);else if(name==='throw')this.tone(140,.12,'triangle',.12);}
 update(stage){if(!this.ctx||this.original||!this.enabled)return;const t=this.ctx.currentTime;if(this.next<t)this.next=t;const notes=[0,7,3,10,7,2,3,-5,0,12,10,7];while(this.next<t+.12){const semitone=notes[this.note%notes.length],base=stage===4?110:146.83;this.tone(base*2**(semitone/12),.36,'sine',.14,this.next);if(this.note%4===0)this.tone(base/2,.75,'triangle',.16,this.next);this.next+=stage===2?.425:.48;this.note++;}}
 async load(file){await this.unlock();if(this.original){this.original.pause();URL.revokeObjectURL(this.original.src);}this.original=new window.Audio(URL.createObjectURL(file));this.original.loop=true;this.original.volume=.35;this.original.muted=!this.enabled;await this.original.play();}
}
