import catalog from './audio-manifest.json';
const defaults={master:.75,music:.28,voices:.9,effects:.72};
export class Audio {
 constructor(){this.enabled=true;this.ctx=null;this.buffers=new Map();this.sources=new Set();this.chantKey='';this.stage=-1;this.original=null;this.failures=[];this.played={};this.levels={...defaults};try{const saved=JSON.parse(localStorage.getItem('arena-audio')||'{}');for(const key of Object.keys(defaults))if(Number.isFinite(saved[key]))this.levels[key]=Math.max(0,Math.min(1,saved[key]));}catch{}}
 async unlock(){
  if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.compressor=this.ctx.createDynamicsCompressor();Object.assign(this.compressor.threshold,{value:-12});this.compressor.ratio.value=4;this.compressor.knee.value=16;this.compressor.attack.value=.003;this.compressor.release.value=.2;this.master.connect(this.compressor);this.compressor.connect(this.ctx.destination);this.buses={};for(const category of ['music','voices','effects']){const gain=this.ctx.createGain();gain.connect(this.master);this.buses[category]=gain;}this.applyLevels();this.ready=this.preload();}
  if(this.ctx.state==='suspended')await this.ctx.resume();return this.ready;
 }
 async preload(){const entries=Object.keys(catalog);let next=0;const worker=async()=>{while(next<entries.length){const name=entries[next++];try{const url=globalThis.__ARENA_AUDIO__?.[name]||new URL(`./audio/${catalog[name].file}`,document.baseURI).href;const response=await fetch(url);if(!response.ok)throw Error(name);this.buffers.set(name,await this.ctx.decodeAudioData(await response.arrayBuffer()));}catch{this.failures.push(name);}}};await Promise.all(Array.from({length:5},worker));return this.failures;}
 applyLevels(){if(!this.ctx)return;this.master.gain.setTargetAtTime(this.enabled?this.levels.master:0,this.ctx.currentTime,.08);for(const category of ['music','voices','effects'])this.buses[category].gain.setTargetAtTime(this.levels[category],this.ctx.currentTime,.08);if(this.original){this.original.volume=this.levels.master*this.levels.music;this.original.muted=!this.enabled;}}
 setLevel(category,value){if(!Object.hasOwn(defaults,category))return;this.levels[category]=Math.max(0,Math.min(1,Number(value)));this.applyLevels();try{localStorage.setItem('arena-audio',JSON.stringify(this.levels));}catch{}}
 toggle(){this.enabled=!this.enabled;this.applyLevels();return this.enabled;}
 play(name,{position=null,volume=1,rate=1,delay=0,offset=0,loop=false,category=catalog[name]?.category||'effects',refDistance=7}={}){
  if(!this.ctx||!this.buffers.has(name)||(!this.enabled&&!loop)||this.sources.size>=32)return null;
  const buffer=this.buffers.get(name);if(offset>=buffer.duration&&!loop)return null;
  const source=this.ctx.createBufferSource(),gain=this.ctx.createGain();source.buffer=buffer;source.playbackRate.value=rate;source.loop=loop;gain.gain.value=volume;source.connect(gain);
  let panner=null;if(position){panner=this.ctx.createPanner();panner.panningModel='equalpower';panner.distanceModel='inverse';panner.refDistance=refDistance;panner.rolloffFactor=.65;panner.maxDistance=95;panner.positionX.value=position.x;panner.positionY.value=position.y;panner.positionZ.value=position.z;gain.connect(panner);panner.connect(this.buses[category]);}else gain.connect(this.buses[category]);
  const entry={source,gain,panner,name,loop};this.sources.add(entry);source.onended=()=>{this.sources.delete(entry);source.disconnect();gain.disconnect();panner?.disconnect();};source.start(this.ctx.currentTime+delay,Math.max(0,offset));this.played[name]=(this.played[name]||0)+1;return entry;
 }
 stop(entry){if(entry&&this.sources.has(entry)){try{entry.source.stop();}catch{}}}
 setStage(stage){if(this.stage===stage)return;this.stage=stage;this.chantKey='';this.stop(this.chant);for(const entry of this.sources)if(entry.name==='stop')this.stop(entry);this.stop(this.music);this.music=null;if(!this.original)this.music=this.play('courtyard-score',{loop:true,volume:stage===0?.85:.6});if(stage>0)this.play('stage-'+stage,{category:'voices',volume:.8});}
 reset(){this.chantKey='';for(const entry of this.sources)if(!entry.loop)this.stop(entry);this.stage=-1;}
 async pause(paused){if(!this.ctx)return;if(paused&&this.ctx.state==='running')await this.ctx.suspend();else if(!paused&&this.ctx.state==='suspended')await this.ctx.resume();if(this.original){if(paused)this.original.pause();else this.original.play().catch(()=>{});}}
 syncSun(sun,playing){if(!this.ctx||!this.buffers.has('doll-chant'))return;if(!playing||sun.red){this.stop(this.chant);this.chant=null;return;}const key=String(sun.cycle);if(this.chantKey===key)return;this.chantKey=key;this.stop(this.chant);const duration=this.buffers.get('doll-chant').duration,rate=duration/sun.phaseDuration,age=Math.max(0,sun.phaseDuration-sun.phase);this.chant=this.play('doll-chant',{position:{x:0,y:5,z:-53},refDistance:42,volume:.95,rate,offset:age*rate});}
 effect(event){if(typeof event==='string')event={type:event};const position=event.position||null,params={position,volume:.7};
  if(event.type==='lose'){if(event.stage===0){this.play('shot',{position:{x:position?.x<0?-8:8,y:1.4,z:-51},refDistance:22,volume:1});this.play('impact',{...params,delay:.07,volume:.8});this.play('body',{...params,delay:.7});this.play('scream',{...params,delay:.12,category:'voices',volume:.7});const now=this.ctx?.currentTime||0;if(now-(this.panicAt||-10)>3){this.panicAt=now;this.play('panic',{position:{x:0,y:1.6,z:0},delay:.45,category:'voices',volume:.55,refDistance:20});}}else this.play('defeat',{volume:.7});}
  else if(event.type==='signal'&&event.red)this.play('stop',{position:{x:0,y:5,z:-53},refDistance:42,volume:.55});
  else if(event.type==='step')this.play('step-'+(event.surface||'sand'),{...params,volume:.45,rate:1+((event.seq||0)%3)*.04});
  else if(event.type==='win'){this.play('victory',{volume:.65});this.play('qualified',{volume:.8,delay:.5});}
  else if(event.type==='glass')this.play('glass',params);else if(event.type==='crack')this.play('crack',params);else if(event.type==='pull')this.play('rope',params);else if(event.type==='throw')this.play('throw',params);else if(event.type==='score'||event.type==='miss'&&event.stage===3)this.play('marble',params);else if(event.type==='land')this.play(event.stage===4?'step-metal':'step-sand',params);
 }
 update(camera,active,moving){if(!this.ctx)return;const listener=this.ctx.listener,position=camera.position,direction=camera.getWorldDirection(camera.position.clone());for(const [name,value]of Object.entries({positionX:position.x,positionY:position.y,positionZ:position.z,forwardX:direction.x,forwardY:direction.y,forwardZ:direction.z,upX:0,upY:1,upZ:0}))if(listener[name])listener[name].value=value;if(active&&!this.music&&!this.original)this.music=this.play('courtyard-score',{loop:true,volume:.85});if(this.music)this.music.gain.gain.setTargetAtTime(active?.85:.12,this.ctx.currentTime,.5);if(active&&moving&&!this.breath)this.breath=this.play('breath',{loop:true,volume:.28});if(this.breath)this.breath.gain.gain.setTargetAtTime(active&&moving?.28:0,this.ctx.currentTime,.4);}
 async load(file){await this.unlock();if(this.original){this.original.pause();URL.revokeObjectURL(this.original.src);}this.stop(this.music);this.music=null;this.original=new window.Audio(URL.createObjectURL(file));this.original.loop=true;this.applyLevels();await this.original.play();}
}
