import './style.css';
import {Game,STAGES,CANDY_POINTS,TRACE_PATH} from './rules.js';
import {View} from './view.js';
import {Audio} from './audio.js';
import {Room,normalizeCode} from './room.js';
const $=s=>document.querySelector(s),game=new Game(),audio=new Audio(),keys=new Set();
let view,paused=false,last=performance.now(),toastUntil=0,tracking=false,trackingTrace=0,shownStatus='',shownStage=-1,rosterKey='',lastRoomStatus='';
// PeerJS publishes these shared relay credentials in its default configuration.
const publicIce={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:['turn:eu-0.turn.peerjs.com:3478','turn:us-0.turn.peerjs.com:3478','turn:eu-0.turn.peerjs.com:3478?transport=tcp','turn:us-0.turn.peerjs.com:3478?transport=tcp'],username:'peerjs',credential:'peerjsp'}]};
const testTurn=import.meta.env.VITE_TEST_TURN_PORT;
const peerOptions=import.meta.env.DEV&&import.meta.env.VITE_PEER_HOST?{host:import.meta.env.VITE_PEER_HOST,port:Number(import.meta.env.VITE_PEER_PORT||9000),path:'/peerjs',secure:false,config:testTurn?{iceServers:[{urls:`turn:127.0.0.1:${testTurn}?transport=tcp`,username:'peerjs',credential:'peerjsp'}],iceTransportPolicy:'relay'}:{iceServers:[]}}:{config:publicIce};
const room=new Room(game,roomUi,toast,peerOptions);
try{view=new View($('#app'));}catch(error){$('#description').textContent='Le navigateur ne peut pas activer la 3D. Essaie Chrome, Edge ou Firefox avec l’accélération graphique activée.';$('#start').disabled=true;console.error(error);}
$('#stage-list').innerHTML=STAGES.map((s,i)=>`<div><span>0${i+1}</span>${s.name}</div>`).join('');$('#steps').innerHTML=STAGES.map(()=>'<span></span>').join('');
const starPath=CANDY_POINTS.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ')+' Z';$('#cookie-outline').setAttribute('d',starPath);$('#cookie-trace').setAttribute('d',starPath);$('#cookie-trace').setAttribute('pathLength','100');
const scoreboard=document.createElement('div');scoreboard.className='scoreboard';scoreboard.hidden=true;$('#app').append(scoreboard);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');toastUntil=performance.now()+3500;}
function clearInput(){keys.clear();tracking=false;room.input={forward:0,side:0};if(!room.active&&game.charging){game.charging=false;game.power=0;}}
function isPaused(){return room.active?Boolean(room.state?.paused):paused;}
function ownPlayer(){return room.state?.players.find(p=>p.id===room.id);}
function setPause(value){if(game.status!=='playing'&&!room.active)return;clearInput();if(room.active){if(!room.isHost){toast('Seul l’hôte peut mettre la partie en pause.');return;}room.pause(value);}else paused=value;$('#pause-overlay').hidden=!value;$('#pause').textContent=value?'▶ REPRENDRE':'Ⅱ PAUSE';if(audio.original){if(value)audio.original.pause();else audio.original.play().catch(()=>toast('Appuie sur SON pour relancer la musique.'));}}
async function unlockAudio(){await audio.unlock().catch(()=>toast('Le son n’est pas disponible dans ce navigateur.'));if(audio.original)audio.original.play().catch(()=>{});}
async function begin(stage=game.stage){if(!view)return;clearInput();if(room.active){if(!room.start()){openLobby();toast(room.isHost?'Attends au moins un autre joueur avant de lancer.':'L’hôte lancera les épreuves.');return;}$('#lobby-overlay').hidden=true;await unlockAudio();return;}paused=false;$('#pause-overlay').hidden=true;$('#pause').textContent='Ⅱ PAUSE';game.reset(stage);await unlockAudio();}
$('#start').onclick=()=>begin(game.status==='won'||game.status==='intro'?0:game.stage);$('#restart').onclick=()=>room.active?openLobby():begin();$('#campaign-reset').onclick=()=>begin(0);$('#pause').onclick=()=>setPause(!isPaused());$('#resume').onclick=()=>setPause(false);
$('#music').onclick=async()=>{await audio.unlock().catch(()=>{});const on=audio.toggle();$('#music').textContent=on?'♫ SON ON':'♫ SON OFF';$('#music').setAttribute('aria-pressed',String(on));if(audio.original&&on&&!isPaused())audio.original.play().catch(()=>{});};$('#audio-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{await audio.load(file);toast('Ta musique est chargée. Elle reste sur ton appareil.');}catch{toast('Impossible de lire ce fichier audio. Essaie un MP3 ou WAV.');}};
function openLobby(){clearInput();$('#lobby-overlay').hidden=false;roomUi();}
$('#multiplayer').onclick=openLobby;$('#room-menu').onclick=openLobby;$('#lobby-close').onclick=()=>{$('#lobby-overlay').hidden=true;clearInput();};
$('#room-create').onclick=async()=>{try{await unlockAudio();$('#room-notice').textContent='Création du salon…';await room.create($('#nickname').value);$('#room-notice').className='';}catch(error){$('#room-notice').textContent=error.message;$('#room-notice').className='error';}};
$('#room-join').onclick=async()=>{try{await unlockAudio();$('#room-notice').textContent='Connexion au salon…';await room.join($('#room-code').value,$('#nickname').value);$('#room-notice').className='';}catch(error){$('#room-notice').textContent=error.message;$('#room-notice').className='error';}};
$('#room-start').onclick=()=>begin();$('#room-leave').onclick=()=>{room.leave();view?.setPlayers([]);shownStatus='';$('#pause-overlay').hidden=true;toast('Tu as quitté le salon.');};
$('#room-copy').onclick=async()=>{const url=new URL(location.href);url.searchParams.set('room',room.code);url.hash='';try{await navigator.clipboard.writeText(url.href);toast('Lien copié. Envoie-le à tes amis !');}catch{$('#room-code').value=url.href;$('#room-code').disabled=false;$('#room-code').focus();$('#room-code').select();toast('Copie le lien sélectionné ou partage le code du salon.');}};
function roomUi(){
 const state=room.state,active=room.active,ready=Boolean(state),pending=active&&!ready;
 if(state?.status==='playing'&&lastRoomStatus!=='playing'&&lastRoomStatus!=='transition'){$('#lobby-overlay').hidden=true;unlockAudio();}lastRoomStatus=state?.status||'';
 $('#room-menu').hidden=!active;$('#room-menu').textContent=room.code?`♟ ${room.code}`:'♟ SALON';$('#room-details').hidden=!ready;$('#room-create').disabled=active;$('#room-join').disabled=active;$('#nickname').disabled=active;$('#room-code').disabled=active;$('#room-copy').disabled=!ready;$('#room-start').hidden=!room.isHost;$('#room-start').disabled=!state||state.players.length<2||!['lobby','finished'].includes(state.status);$('#room-start').textContent=state?.status==='finished'?'Rejouer ensemble →':'Lancer les épreuves →';$('#share-code').textContent=room.code;
 if(pending)$('#room-notice').textContent='Connexion au service multijoueur…';else if(ready){$('#room-notice').textContent=`${state.players.length} / 4 joueurs connectés`;$('#room-notice').className='';}else if(!$('#room-notice').classList.contains('error'))$('#room-notice').textContent='Pas de compte nécessaire.';
 $('#room-wait').textContent=!ready?'':state.status==='lobby'?(room.isHost?'Partage le code ou le lien. Il faut au moins deux joueurs pour commencer.':'Tu es dans le salon. L’hôte lancera la partie.') :state.status==='finished'?'La partie est terminée. L’hôte peut lancer une nouvelle campagne.':'La partie est en cours. Quitter le salon te déconnecte.';
 const signature=JSON.stringify({code:room.code,status:state?.status,players:state?.players.map(p=>[p.id,p.name,p.eliminated,p.game.status])});if(signature!==rosterKey){rosterKey=signature;$('#room-players').replaceChildren();scoreboard.replaceChildren();for(const [i,p]of(state?.players||[]).entries()){const item=document.createElement('li'),name=document.createElement('span'),role=document.createElement('small'),dot=document.createElement('span');dot.className='player-color';dot.style.background=['#9fd4b4','#8cb8f0','#e6ba80','#c5a7ee'][i];name.append(dot,document.createTextNode(p.name+(p.id===room.id?' · toi':'')));role.textContent=p.id===state.hostId?'HÔTE':'CONNECTÉ';item.append(name,role);$('#room-players').append(item);const row=document.createElement('div'),badge=document.createElement('span'),title=document.createElement('b'),status=document.createElement('small');badge.style.background=dot.style.background;title.textContent=p.name;status.textContent=p.eliminated?'SPECTATEUR':['transition','won'].includes(p.game.status)?'QUALIFIÉ':'EN JEU';row.classList.toggle('out',p.eliminated);row.append(badge,title,status);scoreboard.append(row);}}
 scoreboard.hidden=!active||!state||state.status==='lobby';view?.setPlayers(state?.players||[],room.id);
 $('#resume').hidden=active&&!room.isHost;$('#pause-overlay').hidden=!state?.paused&&!paused;$('#pause').textContent=isPaused()?'▶ REPRENDRE':'Ⅱ PAUSE';
}
function actionDown(){if(isPaused()||game.status!=='playing'||!$('#lobby-overlay').hidden)return;const action=game.stage===2?'tug':game.stage===3?'charge':'jump';if(room.active)room.action(action);else game[action]();}
function actionUp(){if(!isPaused()&&game.stage===3){if(room.active)room.action('release');else game.release();}}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(e.target instanceof HTMLInputElement)return;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='escape'&&!$('#lobby-overlay').hidden){$('#lobby-overlay').hidden=true;clearInput();return;}if(k==='escape'||k==='p'){if(!e.repeat)setPause(!isPaused());return;}if(!e.repeat&&k===' ')actionDown();if(!isPaused()&&$('#lobby-overlay').hidden)keys.add(k);});addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.key===' ')actionUp();});
function unfocus(){clearInput();if(room.active){if(room.isHost&&room.state?.status==='playing')room.pause(true);}else if(game.status==='playing')setPause(true);}
addEventListener('blur',unfocus);document.addEventListener('visibilitychange',()=>{if(document.hidden)unfocus();});addEventListener('pagehide',()=>room.leave(false));
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();if(isPaused())return;keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.key));}
for(const id of ['jump','pull','throw']){const b=$('#'+id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);actionDown();});b.addEventListener('pointerup',actionUp);b.addEventListener('pointercancel',()=>{if(room.active)room.action('release');else game.charging=false;});}
$('#aim').oninput=e=>{const aim=Number(e.target.value)/100;if(room.active)room.action('aim',{aim});else game.aim=aim;};
const cookie=$('#candy');
function trace(e){const rect=cookie.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*300,y=(e.clientY-rect.top)/rect.height*300;let accepted;if(room.active){let best=trackingTrace,dist=Infinity;for(let i=trackingTrace;i<Math.min(TRACE_PATH.length,trackingTrace+15);i++){const p=TRACE_PATH[i],d=Math.hypot(p.x-x,p.y-y);if(d<dist){dist=d;best=i;}}accepted=dist<18;if(accepted){trackingTrace=best;room.action('trace',{x,y});}else room.action('crack');}else {accepted=game.tracePoint(x,y);if(!accepted)game.crack();}if(!accepted){tracking=false;toast('Un écart ! Relâche et reprends au point lumineux.');}}
cookie.addEventListener('pointerdown',e=>{if(isPaused()||game.status!=='playing')return;e.preventDefault();const r=cookie.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*300,y=(e.clientY-r.top)/r.height*300,p=TRACE_PATH[game.trace];if(Math.hypot(x-p.x,y-p.y)>23){toast('Commence au point lumineux.');return;}tracking=true;trackingTrace=game.trace;cookie.setPointerCapture(e.pointerId);trace(e);});cookie.addEventListener('pointermove',e=>{if(tracking&&!isPaused())trace(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])cookie.addEventListener(event,()=>tracking=false);
function renderOverlay(){
 let status=game.status;const state=room.state,own=ownPlayer();if(room.active){status=!state?'connecting':state.status==='lobby'?'lobby':state.status==='finished'?'room-finished':'room-playing';}
 const key=status+(state?.players.length||'');if(key===shownStatus&&game.stage===shownStage)return;shownStatus=key;shownStage=game.stage;
 $('#overlay').style.display=['playing','room-playing'].includes(status)?'none':'flex';$('#stage-list').hidden=status!=='intro';$('#campaign-reset').hidden=room.active||!['lost','won'].includes(status);$('#start').hidden=status==='transition';$('#start').disabled=status==='connecting'||status==='room-finished'&&!room.isHost;$('#multiplayer').textContent=room.active?'Voir le salon ♟':'Jouer avec des amis ♟';$('#overlay-hint').textContent=status==='intro'?'ZQSD / WASD / flèches pour bouger · Espace pour sauter. Commandes tactiles disponibles.':STAGES[game.stage].controls;
 if(status==='intro'){$('#overlay-tag').textContent='UNE AVENTURE DE SURVIE EN 3D';$('#headline').innerHTML='Six épreuves.<br><em>Une chance.</em>';$('#description').textContent='Entre dans l’arène. Garde ton sang-froid, choisis ton chemin et survis aux six épreuves, seul ou avec tes amis.';$('#start').innerHTML='Jouer en solo <span>→</span>';return;}
 if(status==='lobby'||status==='connecting'){$('#overlay-tag').textContent='MULTIJOUEUR · SALON ENTRE AMIS';$('#headline').innerHTML='Rassemble<br><em>tes amis.</em>';$('#description').textContent=status==='connecting'?'Connexion au salon…':`Salon ${room.code} · ${state.players.length} / 4 joueurs. ${room.isHost?'Lance les épreuves lorsque tes amis sont prêts.':'L’hôte lancera la partie.'}`;$('#start').innerHTML=room.isHost&&state?.players.length>=2?'Lancer la partie <span>→</span>':'Voir le salon <span>♟</span>';return;}
 if(status==='room-finished'){const winners=state.players.filter(p=>!p.eliminated&&p.game.status==='won');$('#overlay-tag').textContent='PARTIE MULTIJOUEUR TERMINÉE';$('#headline').innerHTML=winners.length?'Les derniers<br><em>survivants.</em>':'L’arène a<br><em>tout gagné.</em>';$('#description').textContent=winners.length?'Victoire : '+winners.map(p=>p.name).join(', ')+'.':'Tous les joueurs ont été éliminés. Rejouez ensemble pour tenter votre chance.';$('#start').innerHTML=room.isHost?'Rejouer ensemble <span>→</span>':'En attente de l’hôte';return;}
 if(status==='lost'){$('#overlay-tag').textContent=`ÉPREUVE 0${game.stage+1} · ÉLIMINÉ`;$('#headline').innerHTML='Pas cette fois.<br><em>Réessaie.</em>';$('#description').textContent=game.message;$('#start').innerHTML='Réessayer cette épreuve <span>↻</span>';}
 else if(status==='transition'){$('#overlay-tag').textContent='ÉPREUVE RÉUSSIE';$('#headline').innerHTML='Tu passes.<br><em>Reste calme.</em>';$('#description').textContent=`Prochaine épreuve : ${STAGES[game.stage+1].name}. ${STAGES[game.stage+1].instruction}`;}
 else if(status==='won'){$('#overlay-tag').textContent='SIX ÉPREUVES · SIX VICTOIRES';$('#headline').innerHTML='Dernier<br><em>survivant.</em>';$('#description').textContent=game.message;$('#start').innerHTML='Rejouer les six épreuves <span>→</span>';}
}
function ui(){
 const stage=STAGES[game.stage],playing=game.status==='playing',state=room.state,own=ownPlayer(),spectating=Boolean(own?.eliminated);$('.player-id b').textContent=String(456+Math.max(0,(state?.players||[]).findIndex(p=>p.id===room.id)));$('#stage-count').textContent=`ÉPREUVE 0${game.stage+1} / 06`;$('#stage-name').textContent=stage.name;$('#steps').querySelectorAll('span').forEach((s,i)=>s.className=i<game.stage?'done':i===game.stage?'active':'');const sec=Math.ceil(state?.remaining??game.remaining);$('#timer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$('.timer-box').classList.toggle('danger',sec<15);$('#status').textContent=spectating?'SPECTATEUR':game.status==='transition'?'QUALIFIÉ · PROCHAINE ÉPREUVE':game.status==='lost'?'ÉLIMINÉ':game.status==='won'?'VAINQUEUR':playing?stage.subtitle.toUpperCase():'JOUEUR EN ATTENTE';$('#movement-controls').hidden=![0,4,5].includes(game.stage)||!playing||spectating;
 $('#candy-panel').hidden=game.stage!==1||!playing;$('#tug-panel').hidden=game.stage!==2||!playing;$('#marble-panel').hidden=game.stage!==3||!playing;$('#pause').disabled=room.active?!room.isHost||!state||!['playing','transition'].includes(state.status):!playing;$('#restart').textContent=room.active?'♟ Salon':'↻ Réessayer';
 const sig=$('#signal'),red=state?.red??game.red;sig.className=game.stage===0&&(playing||spectating)?(red?'red':'green'):'';sig.textContent=state?.status==='transition'?`PROCHAINE ÉPREUVE DANS ${Math.max(1,Math.ceil(state.delay))}…`:!room.active&&game.status==='transition'?`PROCHAINE ÉPREUVE DANS ${Math.max(1,Math.ceil(game.transition))}…`:!playing&&!spectating?'LES SIX ÉPREUVES':game.stage===0?(red?'● FEU ROUGE · IMMOBILE':'● FEU VERT · AVANCE'):game.stage===1?'UNE MAIN CALME':game.stage===2?'TIRE AU BON MOMENT':game.stage===3?'TROIS LANCERS RÉUSSIS':game.stage===4?'OBSERVE LE VERRE':'SAUTE · ESQUIVE · SURVIS';
 const banner=$('#network-banner');banner.hidden=!state||state.status==='lobby'||state.status==='finished';if(!banner.hidden)banner.textContent=state.paused?'Partie en pause · l’hôte doit reprendre':spectating?'Éliminé · tu regardes les survivants':state.status==='transition'?`Épreuve réussie · prochaine dans ${Math.max(1,Math.ceil(state.delay))} secondes`:['transition','won'].includes(game.status)?'Qualifié · en attente des autres joueurs':`${state.players.filter(p=>!p.eliminated).length} survivants · salon ${room.code}`;
 let progress=0;if([0,4,5].includes(game.stage))progress=(6-game.position.z)/(game.stage===4?49:54);if(game.stage===1){const index=room.active&&tracking?Math.max(game.trace,trackingTrace):game.trace;progress=index/(TRACE_PATH.length-1);$('#cookie-trace').setAttribute('stroke-dasharray',`${progress*100} 100`);const p=TRACE_PATH[index];$('#trace-tip').setAttribute('cx',p.x);$('#trace-tip').setAttribute('cy',p.y);$('#trace-progress').textContent=`${Math.round(progress*100)} % DÉCOUPÉ`;$('#strikes').textContent=`${game.strikes} / 3 ÉCARTS`;$('#cookie-crack').setAttribute('opacity',game.strikes?'.8':'0');}if(game.stage===2){progress=game.pull;$('#rhythm-cursor').style.left=`${(state?.elapsed??game.elapsed)%.85/.85*99}%`;$('#rope-marker').style.left=`${Math.max(0,game.pull)*99}%`;}if(game.stage===3){progress=game.hits/3;$('#hits').textContent=`${game.hits} / 3 RÉUSSITES`;$('#misses').textContent=`${game.misses} / 5 ERREURS`;$('#aim').value=game.aim*100;$('#power-fill').style.width=`${game.power*100}%`;$('#power-label').textContent=`${Math.round(game.power*100)} %`;$('#throw').textContent=game.shot?'LANCER EN COURS…':game.charging?'RELÂCHE POUR LANCER':'MAINTENIR POUR LANCER';}$('#bar').style.width=`${Math.max(0,Math.min(1,progress))*100}%`;renderOverlay();
}
function tick(now){
 requestAnimationFrame(tick);const dt=Math.min((now-last)/1000,.04);last=now;const held=arr=>arr.some(k=>keys.has(k)),input={forward:(held(['z','w','arrowup'])?1:0)-(held(['s','arrowdown'])?1:0),side:(held(['d','arrowright'])?1:0)-(held(['q','a','arrowleft'])?1:0)};
 if(room.active)room.input=isPaused()||!$('#lobby-overlay').hidden?{forward:0,side:0}:input;else if(!paused&&$('#lobby-overlay').hidden)game.update(dt,input);
 for(const event of game.events.splice(0)){if(event.type==='stage'){clearInput();view?.load(game.stage);if(game.status==='playing')toast(STAGES[game.stage].instruction);}else{audio.effect(event.type);if(['glass','lose','crack'].includes(event.type)){document.body.classList.add('hit');setTimeout(()=>document.body.classList.remove('hit'),350);}if(event.type==='pull')toast('Traction parfaite !');if(event.type==='score')toast('Dans le cercle !');if(event.type==='miss')toast(game.stage===2?'Trop tôt ou trop tard !':'À côté du cercle. Ajuste ton prochain lancer.');}}
 if(game.status==='playing'&&!isPaused())audio.update(game.stage);if(now>toastUntil)$('#toast').classList.remove('visible');ui();let viewGame=game;if(ownPlayer()?.eliminated){const watched=room.state.players.find(p=>!p.eliminated);if(watched)viewGame={...watched.game,red:room.state.red,broken:new Set(watched.game.broken)};}view?.update(viewGame,dt,isPaused()?game.elapsed:now/1000);
}
requestAnimationFrame(tick);
const invite=normalizeCode(new URL(location.href).searchParams.get('room')||'');if(invite){$('#room-code').value=invite;openLobby();}
export {game,room};
