import './style.css';
import {Game,STAGES,CANDY_POINTS,TRACE_PATH} from './rules.js';
import {View} from './view.js';
import {Audio} from './audio.js';
const $=s=>document.querySelector(s),game=new Game(),audio=new Audio(),keys=new Set();let view,paused=false,last=performance.now(),toastUntil=0,tracking=false,shownStatus='',shownStage=-1;
try{view=new View($('#app'));}catch(error){$('#description').textContent='Le navigateur ne peut pas activer la 3D. Essaie Chrome, Edge ou Firefox avec l’accélération graphique activée.';$('#start').disabled=true;console.error(error);}
$('#stage-list').innerHTML=STAGES.map((s,i)=>`<div><span>0${i+1}</span>${s.name}</div>`).join('');$('#steps').innerHTML=STAGES.map(()=>'<span></span>').join('');
const starPath=CANDY_POINTS.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ')+' Z';$('#cookie-outline').setAttribute('d',starPath);$('#cookie-trace').setAttribute('d',starPath);$('#cookie-trace').setAttribute('pathLength','100');
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');toastUntil=performance.now()+2600;}
function clearInput(){keys.clear();tracking=false;if(game.charging){game.charging=false;game.power=0;}}
function setPause(value){if(game.status!=='playing')return;paused=value;clearInput();$('#pause-overlay').hidden=!paused;$('#pause').textContent=paused?'▶ REPRENDRE':'Ⅱ PAUSE';if(audio.original){if(paused)audio.original.pause();else audio.original.play().catch(()=>toast('Appuie sur SON pour relancer la musique.'));}}
async function begin(stage=game.stage){if(!view)return;clearInput();paused=false;$('#pause-overlay').hidden=true;$('#pause').textContent='Ⅱ PAUSE';game.reset(stage);await audio.unlock().catch(()=>toast('Le son n’est pas disponible dans ce navigateur.'));if(audio.original)audio.original.play().catch(()=>{});}
$('#start').onclick=()=>begin(game.status==='won'||game.status==='intro'?0:game.stage);$('#restart').onclick=()=>begin();$('#campaign-reset').onclick=()=>begin(0);$('#pause').onclick=()=>setPause(!paused);$('#resume').onclick=()=>setPause(false);
$('#music').onclick=async()=>{await audio.unlock().catch(()=>{});const on=audio.toggle();$('#music').textContent=on?'♫ SON ON':'♫ SON OFF';$('#music').setAttribute('aria-pressed',String(on));if(audio.original&&on&&!paused)audio.original.play().catch(()=>{});};$('#audio-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{await audio.load(file);toast('Ta musique est chargée. Elle reste sur ton appareil.');}catch{toast('Impossible de lire ce fichier audio. Essaie un MP3 ou WAV.');}};
function actionDown(){if(paused||game.status!=='playing')return;if(game.stage===2)game.tug();else if(game.stage===3)game.charge();else game.jump();}
function actionUp(){if(!paused&&game.stage===3)game.release();}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(e.target instanceof HTMLInputElement)return;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='escape'||k==='p'){if(!e.repeat)setPause(!paused);return;}if(!e.repeat&&k===' ')actionDown();if(!paused)keys.add(k);});addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.key===' ')actionUp();});addEventListener('blur',()=>{clearInput();if(game.status==='playing')setPause(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.status==='playing')setPause(true);});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();if(paused)return;keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.key));}
for(const id of ['jump','pull','throw']){const b=$('#'+id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);actionDown();});b.addEventListener('pointerup',actionUp);b.addEventListener('pointercancel',()=>{game.charging=false;});}
$('#aim').oninput=e=>{game.aim=Number(e.target.value)/100;};
const cookie=$('#candy');function trace(e){const rect=cookie.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*300,y=(e.clientY-rect.top)/rect.height*300;if(!game.tracePoint(x,y)){game.crack();tracking=false;toast('Un écart ! Relâche et reprends au point lumineux.');}}
cookie.addEventListener('pointerdown',e=>{if(paused||game.status!=='playing')return;e.preventDefault();const r=cookie.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*300,y=(e.clientY-r.top)/r.height*300,p=TRACE_PATH[game.trace];if(Math.hypot(x-p.x,y-p.y)>23){toast('Commence au point lumineux.');return;}tracking=true;cookie.setPointerCapture(e.pointerId);trace(e);});cookie.addEventListener('pointermove',e=>{if(tracking&&!paused)trace(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])cookie.addEventListener(event,()=>tracking=false);
function renderOverlay(){const status=game.status;if(status===shownStatus&&game.stage===shownStage)return;shownStatus=status;shownStage=game.stage;$('#overlay').style.display=status==='playing'?'none':'flex';$('#stage-list').hidden=status!=='intro';$('#campaign-reset').hidden=!['lost','won'].includes(status);$('#start').hidden=status==='transition';$('#overlay-hint').textContent=status==='intro'?'ZQSD / WASD / flèches pour bouger · Espace pour sauter. Commandes tactiles disponibles.':STAGES[game.stage].controls;
 if(status==='intro')return;if(status==='lost'){$('#overlay-tag').textContent=`ÉPREUVE 0${game.stage+1} · ÉLIMINÉ` ;$('#headline').innerHTML='Pas cette fois.<br><em>Réessaie.</em>';$('#description').textContent=game.message;$('#start').innerHTML='Réessayer cette épreuve <span>↻</span>';}
 else if(status==='transition'){$('#overlay-tag').textContent='ÉPREUVE RÉUSSIE';$('#headline').innerHTML='Tu passes.<br><em>Reste calme.</em>';$('#description').textContent=`Prochaine épreuve : ${STAGES[game.stage+1].name}. ${STAGES[game.stage+1].instruction}`;}
 else if(status==='won'){$('#overlay-tag').textContent='SIX ÉPREUVES · SIX VICTOIRES';$('#headline').innerHTML='Dernier<br><em>survivant.</em>';$('#description').textContent=game.message;$('#start').innerHTML='Rejouer les six épreuves <span>→</span>';}}
function ui(){const stage=STAGES[game.stage],playing=game.status==='playing';$('#stage-count').textContent=`ÉPREUVE 0${game.stage+1} / 06`;$('#stage-name').textContent=stage.name;$('#steps').querySelectorAll('span').forEach((s,i)=>s.className=i<game.stage?'done':i===game.stage?'active':'');const sec=Math.ceil(game.remaining);$('#timer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$('.timer-box').classList.toggle('danger',sec<15);$('#status').textContent=game.status==='transition'?'QUALIFIÉ · PROCHAINE ÉPREUVE':game.status==='lost'?'ÉLIMINÉ':game.status==='won'?'VAINQUEUR':playing?stage.subtitle.toUpperCase():'JOUEUR EN ATTENTE';$('#movement-controls').hidden=![0,4,5].includes(game.stage)||!playing;
 $('#candy-panel').hidden=game.stage!==1||!playing;$('#tug-panel').hidden=game.stage!==2||!playing;$('#marble-panel').hidden=game.stage!==3||!playing;$('#pause').disabled=!playing;
 const sig=$('#signal');sig.className=game.stage===0&&playing?(game.red?'red':'green'):'';sig.textContent=game.status==='transition'?`PROCHAINE ÉPREUVE DANS ${Math.max(1,Math.ceil(game.transition))}…`:!playing?'LES SIX ÉPREUVES':game.stage===0?(game.red?'● FEU ROUGE · IMMOBILE':'● FEU VERT · AVANCE'):game.stage===1?'UNE MAIN CALME':game.stage===2?'TIRE AU BON MOMENT':game.stage===3?'TROIS LANCERS RÉUSSIS':game.stage===4?'OBSERVE LE VERRE':'SAUTE · ESQUIVE · SURVIS';
 let progress=0;if([0,4,5].includes(game.stage))progress=(6-game.position.z)/(game.stage===4?49:54);if(game.stage===1){progress=game.trace/(TRACE_PATH.length-1);$('#cookie-trace').setAttribute('stroke-dasharray',`${progress*100} 100`);const p=TRACE_PATH[game.trace];$('#trace-tip').setAttribute('cx',p.x);$('#trace-tip').setAttribute('cy',p.y);$('#trace-progress').textContent=`${Math.round(progress*100)} % DÉCOUPÉ`;$('#strikes').textContent=`${game.strikes} / 3 ÉCARTS`;$('#cookie-crack').setAttribute('opacity',game.strikes?'.8':'0');}if(game.stage===2){progress=game.pull;$('#rhythm-cursor').style.left=`${game.elapsed%.85/.85*99}%`;$('#rope-marker').style.left=`${Math.max(0,game.pull)*99}%`;}if(game.stage===3){progress=game.hits/3;$('#hits').textContent=`${game.hits} / 3 RÉUSSITES`;$('#misses').textContent=`${game.misses} / 5 ERREURS`;$('#aim').value=game.aim*100;$('#power-fill').style.width=`${game.power*100}%`;$('#power-label').textContent=`${Math.round(game.power*100)} %`;$('#throw').textContent=game.shot?'LANCER EN COURS…':game.charging?'RELÂCHE POUR LANCER':'MAINTENIR POUR LANCER';}$('#bar').style.width=`${Math.max(0,Math.min(1,progress))*100}%`;renderOverlay();}
function tick(now){requestAnimationFrame(tick);const dt=Math.min((now-last)/1000,.04);last=now;const held=arr=>arr.some(k=>keys.has(k));if(!paused)game.update(dt,{forward:(held(['z','w','arrowup'])?1:0)-(held(['s','arrowdown'])?1:0),side:(held(['d','arrowright'])?1:0)-(held(['q','a','arrowleft'])?1:0)});for(const event of game.events.splice(0)){if(event.type==='stage'){clearInput();view?.load(game.stage);if(game.status==='playing')toast(STAGES[game.stage].instruction);}else{audio.effect(event.type);if(['glass','lose','crack'].includes(event.type)){document.body.classList.add('hit');setTimeout(()=>document.body.classList.remove('hit'),350);}if(event.type==='pull')toast('Traction parfaite !');if(event.type==='score')toast('Dans le cercle !');if(event.type==='miss')toast(game.stage===2?'Trop tôt ou trop tard !':'À côté du cercle. Ajuste ton prochain lancer.');}}
 if(game.status==='playing'&&!paused)audio.update(game.stage);if(now>toastUntil)$('#toast').classList.remove('visible');ui();view?.update(game,dt,paused?game.elapsed:now/1000);}
requestAnimationFrame(tick);

export {game};
