import {resetSun,advanceSun} from './sun-cycle.js';
import {Game,STAGES,TRACE_PATH} from './rules.js';
export const MAX_PLAYERS=4;
export const VERSION=2;
export const GAME_FIELDS=['stage','status','remaining','position','vy','grounded','elapsed','red','phase','grace','transition','message','trace','strikes','pull','lastPull','aim','power','charging','shot','hits','misses','targetX','phaseDuration','cycle','death'];
export function cleanName(value){return typeof value==='string'?value.replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,18)||'Joueur':'Joueur';}
export function snapshotGame(game){const data={};for(const key of GAME_FIELDS)data[key]=key==='phase'&&!Number.isFinite(game[key])?0:game[key];return {...data,position:{...game.position},broken:[...game.broken]};}
export function applySnapshot(game,data){if(!data||!Number.isInteger(data.stage)||data.stage<0||data.stage>=STAGES.length||!['intro','playing','transition','won','lost'].includes(data.status)||!data.position||![data.position.x,data.position.y,data.position.z,data.remaining,data.elapsed].every(Number.isFinite))return false;const oldStage=game.stage,oldStatus=game.status,oldRed=game.red,oldHits=game.hits;for(const key of GAME_FIELDS)if(Object.hasOwn(data,key))game[key]=data[key];game.position={...data.position};game.broken=new Set(Array.isArray(data.broken)?data.broken.slice(0,16):[]);if(oldStage!==game.stage)game.events.push({type:'stage',stage:game.stage});if(oldStatus!==game.status){if(game.status==='lost')game.events.push({type:'lose'});if(['transition','won'].includes(game.status))game.events.push({type:'win'});}if(oldRed!==game.red)game.events.push({type:'signal',red:game.red});if(game.hits>oldHits)game.events.push({type:'score'});return true;}
export class Match {
 constructor(hostId,hostName,hostGame=new Game(),random=Math.random){this.hostId=hostId;this.players=new Map();this.stage=0;this.status='lobby';this.paused=false;this.epoch=0;this.clock=0;this.delay=0;this.broken=new Set();this.random=random;resetSun(this);this.effects=[];this.effectSeq=0;this.add(hostId,hostName,hostGame);}
 add(id,name,game=new Game()){if(this.status!=='lobby'||this.players.size>=MAX_PLAYERS||this.players.has(id))return false;this.players.set(id,{id,name:cleanName(name),game,eliminated:false,input:{forward:0,side:0},inputAt:this.clock,lastSeq:-1,budget:0,budgetTime:this.clock,effectCursor:game.effectSeq||0});return true;}
 remove(id){this.players.delete(id);this.settle();}
 start(){if(this.players.size<2||!['lobby','finished'].includes(this.status))return false;for(const p of this.players.values())p.eliminated=false;this.load(0);return true;}
 load(stage){this.stage=stage;this.status='playing';this.paused=false;this.epoch++;this.delay=0;resetSun(this);this.effects=[];this.elapsed=0;this.pull=.5;this.broken=new Set();let index=0;for(const p of this.players.values()){p.game.reset(stage);p.game.broken=this.broken;p.effectCursor=p.game.effectSeq;p.input={forward:0,side:0};p.game.position.x=stage===4?-1.65:(index-(this.players.size-1)/2)*1.2;p.game.position.z=6+index*.2;index++;if(p.eliminated){p.game.status='lost';p.game.message='Tu es spectateur. Les survivants continuent la partie.';}}}
 input(id,value,seq,epoch=this.epoch){const p=this.players.get(id);if(!p||epoch!==this.epoch||!Number.isInteger(seq)||seq<=p.lastSeq||!value||![-1,0,1].includes(value.forward)||![-1,0,1].includes(value.side))return false;p.lastSeq=seq;p.input={forward:value.forward,side:value.side};p.inputAt=this.clock;return true;}
 command(id,type,value={},epoch=this.epoch){const p=this.players.get(id);if(!p||epoch!==this.epoch||this.status!=='playing'||this.paused||p.eliminated||p.game.status!=='playing')return false;if(this.clock-p.budgetTime>1){p.budget=0;p.budgetTime=this.clock;}if(++p.budget>160)return false;const g=p.game;
 switch(type){case 'jump':g.jump();break;case 'trace':if(this.stage!==1||![value.x,value.y].every(Number.isFinite)||value.x<0||value.x>300||value.y<0||value.y>300)return false;g.tracePoint(value.x,value.y);break;case 'crack':if(this.stage!==1)return false;g.crack();break;case 'tug':if(this.stage!==2)return false;g.pull=this.pull;g.elapsed=this.elapsed;{g.tug(1/Math.sqrt(this.alive().length));this.pull=g.pull;for(const team of this.alive()){team.game.pull=this.pull;if(this.pull>=1)team.game.win();}}break;case 'charge':g.charge();break;case 'release':g.release();break;case 'aim':if(this.stage!==3||!Number.isFinite(value.aim))return false;g.aim=Math.max(-1,Math.min(1,value.aim));break;default:return false;}
 this.collectEffects();this.settle();return true;}
 alive(){return [...this.players.values()].filter(p=>!p.eliminated);}
 settle(){if(this.status!=='playing')return;for(const p of this.players.values())if(p.game.status==='lost')p.eliminated=true;const alive=this.alive();if(!alive.length){this.status='finished';return;}if(alive.every(p=>p.game.status==='transition'||p.game.status==='won')){this.status=this.stage===5?'finished':'transition';this.delay=3.2;}}
 update(dt){this.clock+=dt;if(this.paused||this.status==='lobby'||this.status==='finished')return;if(this.status==='transition'){this.delay-=dt;if(this.delay<=0)this.load(this.stage+1);return;}this.elapsed+=dt;
 if(this.stage===0&&advanceSun(this,dt,this.random))this.recordEffect({type:'signal',red:this.red,position:{x:0,y:5,z:-53}});
 for(const p of this.alive()){const g=p.game;if(g.status!=='playing')continue;if(this.stage===0){g.externalSun=true;g.red=this.red;g.phase=this.phase;g.phaseDuration=this.phaseDuration;g.cycle=this.cycle;g.grace=this.grace;}if(this.stage===2)g.pull=this.pull;if(this.clock-p.inputAt>.5)p.input={forward:0,side:0};g.update(dt,p.input);}
 if(this.stage===2)this.pull=Math.max(0,this.pull-dt*.024);this.collectEffects();this.settle();}
 recordEffect(effect,playerId=''){this.effects.push({...effect,id:++this.effectSeq,playerId,epoch:this.epoch,stage:this.stage,at:this.elapsed});if(this.effects.length>32)this.effects.shift();}
 collectEffects(){for(const p of this.players.values())for(const event of p.game.effects){if(event.seq<=p.effectCursor)continue;p.effectCursor=event.seq;if(!['stage','signal'].includes(event.type))this.recordEffect(event,p.id);}}
 snapshot(){this.collectEffects();return {version:VERSION,hostId:this.hostId,stage:this.stage,status:this.status,paused:this.paused,elapsed:this.elapsed||0,red:Boolean(this.red),remaining:Math.max(0,STAGES[this.stage].time-(this.elapsed||0)),epoch:this.epoch,delay:this.delay,sun:{red:Boolean(this.red),phase:this.phase,phaseDuration:this.phaseDuration,cycle:this.cycle,grace:this.grace},effects:this.effects,players:[...this.players.values()].map(p=>({id:p.id,name:p.name,eliminated:p.eliminated,game:snapshotGame(p.game)}))};}
}
