import {Peer} from 'peerjs';
import {MAX_BUFFERED_BYTES,statePacket,shouldSendInput,freshEffect} from './network-sync.js';
import {Match,MAX_PLAYERS,VERSION,applySnapshot,cleanName} from './match.js';
const PREFIX='arena-six-v2-';
const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
export function roomCode(){const bytes=crypto.getRandomValues(new Uint8Array(8));return [...bytes].map(v=>alphabet[v%alphabet.length]).join('');}
export function normalizeCode(value){if(typeof value!=='string')return '';try{const url=new URL(value);value=url.searchParams.get('room')||'';}catch{}const code=value.trim().toUpperCase();return /^[A-HJ-NP-Z2-9]{8}$/.test(code)?code:'';}
export class Room {
 constructor(game,onChange=()=>{},onNotice=()=>{},peerOptions={}){this.game=game;this.onChange=onChange;this.onNotice=onNotice;this.peerOptions=peerOptions;this.connections=new Map();this.peer=null;this.match=null;this.state=null;this.code='';this.id='';this.role='';this.seq=0;this.pending=false;this.input={forward:0,side:0};this.name='';this.effects=[];this.effectCursor=0;this.sendAt=0;this.tickAt=0;this.timers=new Set();this.lastSentInput=null;this.lastSentEpoch=-1;this.metrics={sentBytes:0,skippedSnapshots:0,packets:0,uploadBytesPerSecond:0};this.encoder=new TextEncoder();this.trafficAt=performance.now();this.trafficBytes=0;}
 get active(){return Boolean(this.peer);}
 get isHost(){return this.role==='host';}
 later(fn,ms){const timer=setTimeout(()=>{this.timers.delete(timer);fn();},ms);this.timers.add(timer);return timer;}
 async create(name){this.leave(false);this.role='host';this.name=cleanName(name);this.code=roomCode();this.game.reset(0,false);await this.open(PREFIX+this.code);this.match=new Match(this.id,this.name,this.game);this.startLoop();this.publish();return this.code;}
 async join(code,name){const normalized=normalizeCode(code);if(!normalized)throw Error('Entre les 8 caractères du code ou colle le lien d’invitation.');this.leave(false);this.role='guest';this.name=cleanName(name);this.code=normalized;this.game.reset(0,false);await this.open();return new Promise((resolve,reject)=>{const connection=this.peer.connect(PREFIX+this.code,{reliable:true,serialization:'json'});this.hostConnection=connection;this.pending=true;this.rejectJoin=reject;let welcomed=false;const timeout=this.later(()=>{if(!welcomed){reject(Error('Le salon ne répond pas. Vérifie le code et que l’hôte est toujours connecté.'));this.leave();}},18000);
 connection.on('open',()=>connection.send({type:'hello',version:VERSION,name:this.name}));connection.on('data',message=>{if(this.hostConnection!==connection||!message||message.version!==VERSION)return;if(message.type==='error'){clearTimeout(timeout);this.timers.delete(timeout);reject(Error(message.message||'Connexion refusée.'));this.leave();return;}if(message.type==='state'){if(!this.acceptState(message.state))return;if(!welcomed){welcomed=true;this.pending=false;this.rejectJoin=null;clearTimeout(timeout);this.timers.delete(timeout);resolve(this.code);}this.onChange();}});connection.on('close',()=>{if(this.hostConnection!==connection)return;const text=welcomed?'L’hôte a quitté le salon. La partie est terminée.':'La connexion au salon a été fermée.';if(!welcomed)reject(Error(text));this.leave();this.onNotice(text);});connection.on('error',()=>{if(this.hostConnection!==connection)return;const text='La connexion directe n’a pas pu être établie. Essaie un autre réseau.';if(!welcomed)reject(Error(text));this.leave();this.onNotice(text);});this.startLoop();});}
 open(id){return new Promise((resolve,reject)=>{let settled=false;const peer=new Peer(id,{debug:0,secure:true,...this.peerOptions});this.peer=peer;this.pending=true;this.onChange();const timeout=this.later(()=>{if(!settled){reject(Error('Le service multijoueur ne répond pas. Réessaie dans un instant.'));this.leave();}},15000);
 peer.on('open',peerId=>{if(this.peer!==peer)return;settled=true;clearTimeout(timeout);this.timers.delete(timeout);this.id=peerId;this.pending=false;resolve(peerId);});peer.on('connection',connection=>{if(this.peer===peer&&this.isHost)this.admit(connection);else connection.close();});peer.on('error',error=>{if(this.peer!==peer)return;const message=error.type==='peer-unavailable'?'Ce salon n’existe plus. Demande un nouveau code à l’hôte.':error.type==='unavailable-id'?'Ce code est déjà utilisé. Crée un nouveau salon.':'Connexion multijoueur impossible. Réessaie ou change de réseau.';if(!settled){clearTimeout(timeout);reject(Error(message));this.leave();}else if(error.type==='peer-unavailable'){this.rejectJoin?.(Error(message));this.onNotice(message);this.leave();}else this.onNotice(message);});peer.on('disconnected',()=>{if(this.peer!==peer)return;this.onNotice('Le service des invitations est déconnecté. Tentative de reconnexion…');this.later(()=>{if(this.peer===peer&&!peer.destroyed&&peer.disconnected)peer.reconnect();},1200);});});}
 admit(connection){let accepted=false,lastSeq=-1;const reject=message=>{connection.send({version:VERSION,type:'error',message});this.later(()=>connection.close(),200);};const timeout=this.later(()=>{if(!accepted)connection.close();},8000);
 connection.on('data',message=>{if(!message||message.version!==VERSION||!this.isHost||!this.match||this.peer?.destroyed)return;if(!accepted){if(message.type!=='hello')return;if(!this.match||this.match.status!=='lobby'){reject('La partie a déjà commencé. Attends le prochain salon.');return;}if(this.connections.has(connection.peer)||!this.match.add(connection.peer,message.name)){reject(`Le salon est complet (${MAX_PLAYERS} joueurs maximum).`);return;}accepted=true;clearTimeout(timeout);this.timers.delete(timeout);this.connections.set(connection.peer,connection);this.publish();return;}
 if(!Number.isInteger(message.seq)||message.seq<=lastSeq)return;lastSeq=message.seq;if(message.type==='input')this.match.input(connection.peer,message.value,message.seq,message.epoch);else if(message.type==='action')this.match.command(connection.peer,message.action,message.value,message.epoch);});
 connection.on('close',()=>{clearTimeout(timeout);this.timers.delete(timeout);if(this.connections.get(connection.peer)===connection){this.connections.delete(connection.peer);this.match?.remove(connection.peer);this.publish();this.onNotice('Un joueur a quitté le salon.');}});connection.on('error',()=>connection.close());}
 acceptState(state){if(!state||state.version!==VERSION||!Array.isArray(state.players)||state.players.length>MAX_PLAYERS||!['lobby','playing','transition','finished'].includes(state.status)||!Number.isInteger(state.epoch))return false;const own=state.players.find(p=>p.id===this.id);if(!own||!applySnapshot(this.game,own.game))return false;const wasEpoch=this.state?.epoch;this.state=state;this.readEffects(state);if(wasEpoch!==state.epoch){this.input={forward:0,side:0};if(!this.game.events.some(e=>e.type==='stage'))this.game.events.push({type:'stage',stage:state.stage});}return true;}
 readEffects(state){for(const effect of state.effects||[]){if(!Number.isInteger(effect.id)||effect.id<=this.effectCursor)continue;this.effectCursor=effect.id;if(effect.epoch===state.epoch&&freshEffect(effect,state.elapsed))this.effects.push(effect);}}
 traffic(message){const bytes=this.encoder.encode(JSON.stringify(message)).length;this.metrics.sentBytes+=bytes;this.metrics.packets++;this.trafficBytes+=bytes;const now=performance.now();if(now-this.trafficAt>=1000){this.metrics.uploadBytesPerSecond=Math.round(this.trafficBytes*1000/(now-this.trafficAt));this.trafficBytes=0;this.trafficAt=now;}}
 publish(){if(!this.match)return;this.state=this.match.snapshot();this.readEffects(this.state);for(const p of this.match.players.values())if(p.id!==this.id)p.game.events.length=0;for(const conn of this.connections.values())if(conn.open){if(conn.dataChannel?.bufferedAmount>MAX_BUFFERED_BYTES){this.metrics.skippedSnapshots++;continue;}try{const message=statePacket(this.state,conn.arenaEffectCursor||0);conn.send(message);this.traffic(message);conn.arenaEffectCursor=this.state.effects.at(-1)?.id||conn.arenaEffectCursor||0;}catch{}}this.onChange();}

 startLoop(){clearInterval(this.loop);this.tickAt=performance.now();this.sendAt=0;this.loop=setInterval(()=>{if(!this.peer)return;const now=performance.now(),dt=Math.min(.2,(now-this.tickAt)/1000);this.tickAt=now;if(this.isHost&&this.match){this.match.input(this.id,this.input,++this.seq,this.match.epoch);for(let t=0;t<dt;t+=1/60)this.match.update(Math.min(1/60,dt-t));if(now-this.sendAt>=80){this.sendAt=now;this.publish();}}else if(this.hostConnection?.open&&now-this.sendAt>=50){const epoch=this.state?.epoch||0;if(shouldSendInput(this.input,this.lastSentInput,now-this.sendAt,epoch,this.lastSentEpoch)){this.sendAt=now;this.lastSentInput={...this.input};this.lastSentEpoch=epoch;this.hostConnection.send({type:'input',version:VERSION,seq:++this.seq,epoch,value:this.input});}}},1000/60);}
 action(action,value={}){if(this.isHost&&this.match){const status=this.game.status;if(this.match.command(this.id,action,value,this.match.epoch)&&this.game.status!==status)this.publish();}else if(this.hostConnection?.open)this.hostConnection.send({type:'action',version:VERSION,seq:++this.seq,epoch:this.state?.epoch||0,action,value});}
 start(){if(this.isHost&&this.match?.start()){this.input={forward:0,side:0};this.publish();return true;}return false;}
 pause(value){if(!this.isHost||!this.match)return false;this.match.paused=value;for(const p of this.match.players.values())p.input={forward:0,side:0};this.input={forward:0,side:0};this.publish();return true;}
 leave(notify=true){clearInterval(this.loop);for(const timer of this.timers)clearTimeout(timer);this.timers.clear();const peer=this.peer;this.peer=null;this.hostConnection=null;this.match=null;this.state=null;this.role='';this.code='';this.id='';this.pending=false;this.rejectJoin=null;this.seq=0;this.effectCursor=0;this.effects=[];this.lastSentInput=null;this.lastSentEpoch=-1;this.connections.clear();peer?.destroy();this.input={forward:0,side:0};if(notify){if(peer)this.game.reset(0,false);this.onChange();}}
}
