import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import {STAGES,SAFE_GLASS,OBSTACLES,HURDLES,PITS,BEAMS,CANDY_POINTS,marbleLanding} from './rules.js';
const palette={green:0x176b60,pink:0xf04980,skin:0xd5a17f,wall:0xdbaca3,sand:0xc4ae82,dark:0x121827};
const material=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.75,...extra});
function mesh(geometry,mat,parent,x=0,y=0,z=0){const obj=new THREE.Mesh(geometry,mat);obj.position.set(x,y,z);obj.castShadow=true;obj.receiveShadow=true;parent.add(obj);return obj;}
function box(parent,w,h,d,color,x=0,y=0,z=0,extra={}){return mesh(new THREE.BoxGeometry(w,h,d),material(color,extra),parent,x,y,z);}
function sphere(parent,r,color,x=0,y=0,z=0,sx=1,sy=1,sz=1){const o=mesh(new THREE.SphereGeometry(r,20,16),material(color),parent,x,y,z);o.scale.set(sx,sy,sz);return o;}
function capsule(parent,r,len,color,x,y,z){return mesh(new THREE.CapsuleGeometry(r,len,6,12),material(color),parent,x,y,z);}
function label(text,color='#ecf7ec',bg='transparent',w=512,h=128){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');if(bg!=='transparent'){ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);}ctx.fillStyle=color;ctx.font=`700 ${Math.floor(h*.54)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,w/2,h/2);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function sign(parent,text,x,y,z,w=5,color='#fff',bg='#1b3337'){const o=new THREE.Mesh(new THREE.PlaneGeometry(w,w/4),new THREE.MeshBasicMaterial({map:label(text,color,bg),transparent:true,side:THREE.DoubleSide}));o.position.set(x,y,z);parent.add(o);return o;}
function groundTexture(){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#c8b58a';ctx.fillRect(0,0,256,256);for(let i=0;i<9000;i++){const v=150+Math.floor(Math.random()*60);ctx.fillStyle=`rgba(${v},${v-16},${v-43},.25)`;ctx.fillRect(Math.random()*256,Math.random()*256,1+Math.random()*2,1);}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(8,28);t.colorSpace=THREE.SRGBColorSpace;return t;}
function humanoid(parent,{color=palette.green,number='456',skin=palette.skin,guard=false}={}){
 const rig=new THREE.Group();parent.add(rig);const torso=capsule(rig,.24,.43,color,0,1.12,0);torso.scale.set(1.25,1,.76);
 const hips=capsule(rig,.22,.06,color,0,.8,0);hips.scale.set(1.25,1,.8);
 const neck=capsule(rig,.08,.12,skin,0,1.58,0);const head=new THREE.Group();head.position.y=1.77;rig.add(head);
 sphere(head,.21,guard?0x171820:skin,0,0,0,.86,1.18,.9);
 if(guard){sign(head,'△',0,.01,-.195,.22,'#efefef');}else{
 sphere(head,.212,0x211b1a,0,.08,.025,.88,.9,.83);sphere(head,.065,skin,-.18,-.025,0,.45,1,.7);sphere(head,.065,skin,.18,-.025,0,.45,1,.7);
 sphere(head,.035,skin,0,-.02,-.18,.65,.7,1);for(const x of [-.075,.075]){sphere(head,.022,0xf1e6d7,x,.035,-.176,1,.55,.5);sphere(head,.011,0x261c18,x,.035,-.19,1,1,.4);}box(head,.065,.011,.006,0x86534e,0,-.095,-.18);
 }
 const limbs={legs:[],arms:[]};for(const s of [-1,1]){
 const leg=new THREE.Group();leg.position.set(s*.14,.79,0);rig.add(leg);capsule(leg,.105,.47,color,0,-.31,0);box(leg,.035,.6,.017,0xe3e6da,s*.085,-.28,-.075);box(leg,.2,.13,.33,0xe4e4d9,0,-.7,-.055);limbs.legs.push(leg);
 const arm=new THREE.Group();arm.position.set(s*.32,1.4,0);rig.add(arm);capsule(arm,.085,.43,color,0,-.29,0);box(arm,.023,.47,.018,0xe3e6da,s*.058,-.25,-.067);sphere(arm,.08,guard?0x18191d:skin,0,-.61,0,.8,1.15,.85);limbs.arms.push(arm);
 }
 const numberSigns=[];if(!guard){box(rig,.026,.65,.01,0xcfded2,0,1.16,-.186);numberSigns.push(sign(rig,number,0,1.24,.193,.3,'#f7fffa','#194b40'),sign(rig,number,-.1,1.3,-.194,.16,'#f7fffa','#194b40'));}
 return {rig,head,...limbs,uniformColor:color,number,numberSigns,setIdentity(nextColor,nextNumber){if(this.uniformColor!==nextColor){rig.traverse(o=>{if(o.material?.color?.getHex()===this.uniformColor&&!o.material.map)o.material.color.setHex(nextColor);});this.uniformColor=nextColor;}if(this.number!==nextNumber){for(const patch of numberSigns){patch.material.map.dispose();patch.material.map=label(nextNumber,'#f7fffa','#194b40');}this.number=nextNumber;}},animate(t,movement=0){this.legs.forEach((l,i)=>l.rotation.x=Math.sin(t*11+i*Math.PI)*.58*movement);this.arms.forEach((l,i)=>l.rotation.x=-Math.sin(t*11+i*Math.PI)*.48*movement);torso.position.y=1.12+Math.sin(t*22)*.018*movement;}};
}
export class View {
 constructor(container){this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,180);this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.18;container.prepend(this.renderer.domElement);this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.22,.6,.9);this.composer.addPass(this.bloom);this.floorTexture=groundTexture();this.stage=-1;this.remoteRoster=[];this.remoteActors=new Map();this.lastPosition=new THREE.Vector3();this.camera.position.set(9,7,17);addEventListener('resize',()=>this.resize());}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);this.composer.setSize(innerWidth,innerHeight);}
 clear(){if(this.world){this.world.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of(Array.isArray(o.material)?o.material:[o.material])){if(m.map&&m.map!==this.floorTexture)m.map.dispose();m.dispose();}});this.scene.remove(this.world);}for(const l of this.lights||[]){l.dispose?.();this.scene.remove(l);}this.remoteActors?.clear();this.world=new THREE.Group();this.scene.add(this.world);this.lights=[];this.npcs=[];this.tiles=[];this.beams=[];this.doll=null;this.target=null;this.ball=null;this.rope=null;}
 lighting(dark){this.scene.background=new THREE.Color(dark?'#111522':'#b7d8df');this.scene.fog=new THREE.Fog(dark?'#111522':'#b7d8df',30,95);const hemi=new THREE.HemisphereLight(dark?0x7c94c4:0xd8edff,dark?0x302033:0xa5865c,dark?1.3:2.3);this.scene.add(hemi);this.lights.push(hemi);const sun=new THREE.DirectionalLight(dark?0xa8c9ff:0xffe5c1,dark?2.4:3.2);sun.position.set(-12,24,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-22,right:22,top:65,bottom:-30});sun.shadow.bias=-.0003;this.scene.add(sun);this.lights.push(sun);if(dark){for(const [x,col] of [[-10,0xff4781],[10,0x54dfcb]]){const l=new THREE.PointLight(col,80,55,1.5);l.position.set(x,6,-18);this.scene.add(l);this.lights.push(l);}}}
 floor(z= -22,length=68,width=22,y=-.12){return mesh(new THREE.BoxGeometry(width,.24,length),material(palette.sand,{map:this.floorTexture}),this.world,0,y,z);}
 walls(dark=false){for(const x of [-11.3,11.3]){box(this.world,.6,9,74,dark?0x202436:palette.wall,x,4.4,-24);for(let z=8;z>-58;z-=7){box(this.world,.75,9,.3,dark?0x393e53:0xf2d4bb,x,4.4,z);box(this.world,.04,.12,4.5,0x7ce6ca,x+(x>0?-.33:.33),3.4,z-3,{emissive:0x5cd2b2,emissiveIntensity:1.1});}}box(this.world,23,9,.6,dark?0x202436:palette.wall,0,4.4,-58);}
 exit(z=-49){box(this.world,10,.03,.16,0xecdf97,0,.04,z,{emissive:0xeec65b,emissiveIntensity:.4});for(const x of [-3.8,3.8])box(this.world,.25,5,.3,0xedc067,x,2.5,z-2,{emissive:0xcb9d3d,emissiveIntensity:.5});box(this.world,8,.25,.3,0xedc067,0,5,z-2,{emissive:0xcb9d3d,emissiveIntensity:.5});sign(this.world,'ARRIVÉE',0,4.4,z-1.8,5,'#fff8d3');}
 guards(z=-51){for(const x of [-8,8]){const p=humanoid(this.world,{color:palette.pink,guard:true});p.rig.position.set(x,0,z);p.rig.rotation.y=Math.PI;}}
 load(stage){this.clear();this.stage=stage;const dark=[2,4,5].includes(stage);this.lighting(dark);this.walls(dark);this.player=humanoid(this.world);this.player.rig.position.set(0,0,6);this.lastPosition.set(0,0,6);this.guards();sign(this.world,`0${stage+1} / ${STAGES[stage].name.toUpperCase()}`,0,7,-57.6,16,'#faf4e6',dark?'#252638':'#b87471');
 if(stage===0){this.floor();this.exit();for(const o of OBSTACLES){box(this.world,o.w,o.h,o.d,0xb48369,o.x,o.h/2,o.z);box(this.world,o.w,.08,o.d+.04,0xf0dbb0,o.x,o.h,o.z);}for(let i=0;i<20;i++){const npc=humanoid(this.world,{number:String(101+i),skin:[0xd5a17f,0x8d5e43,0xedc2a4][i%3]});npc.rig.position.set((i%5-2)*3,0,8+Math.floor(i/5)*1.8);this.npcs.push(npc);}this.doll=humanoid(this.world,{color:0xeab33e,number:''});this.doll.rig.position.set(0,0,-53);this.doll.rig.scale.setScalar(3.1);mesh(new THREE.CylinderGeometry(.32,.65,.85,24),material(0xe18730),this.doll.rig,0,.95,0);for(const x of [-7,7]){capsule(this.world,.3,7,0x72543b,x,3.5,-54);for(let i=0;i<5;i++)sphere(this.world,2.1,0x839664,x+Math.sin(i*2)*1.7,7+Math.cos(i)*1.1,-54+Math.cos(i*2)*1.2);}for(let i=0;i<8;i++){sphere(this.world,2.4,0xe4e9dd,-10+i*3,5.8,-58,.9,.3,.08);} }
 if(stage===1){this.floor();box(this.world,5.5,.3,4,0x704333,0,.95,0);for(const x of [-2,2])for(const z of [-1.5,1.5])box(this.world,.15,1.0,.15,0x55332b,x,.45,z);const tray=mesh(new THREE.CylinderGeometry(1.6,1.6,.08,64),material(0xb5ad9e,{metalness:.8,roughness:.35}),this.world,0,1.16,0);mesh(new THREE.CylinderGeometry(1.35,1.35,.1,64),material(0xc38a43,{roughness:.96}),this.world,0,1.24,0);const points=CANDY_POINTS.map(p=>new THREE.Vector3((p.x-150)/105,1.3,(p.y-150)/105));const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x755022}));this.world.add(line);this.player.rig.position.set(0,0,3);this.player.rig.rotation.y=0;for(const x of [-6,6]){const guard=humanoid(this.world,{color:palette.pink,guard:true});guard.rig.position.set(x,0,-5);} }
 if(stage===2){this.floor(-18,30,8,-7);for(const z of [3,-10]){box(this.world,10,.3,9,0x394253,0,-.16,z);for(const x of [-4.8,4.8])box(this.world,.15,.15,9,0xf37d9c,x,.1,z);}this.rope=mesh(new THREE.CylinderGeometry(.035,.035,19,12),material(0xc8ae7c),this.world,0,1.1,-3);this.rope.rotation.x=Math.PI/2;for(let i=0;i<6;i++){const p=humanoid(this.world,{number:String(210+i)});p.rig.position.set((i%2?1:-1)*.45,0,4+Math.floor(i/2)*1.2);this.npcs.push(p);const enemy=humanoid(this.world,{color:0x31547b,number:String(310+i)});enemy.rig.position.set((i%2?1:-1)*.45,0,-8-Math.floor(i/2)*1.2);enemy.rig.rotation.y=Math.PI;this.npcs.push(enemy);}sign(this.world,'GARDE LE RYTHME',0,4,-16,9,'#f8f2da');}
 if(stage===3){this.floor();this.player.rig.position.z=5;for(let i=0;i<10;i++){const x=i%2?-10:10,z=-3-Math.floor(i/2)*9;box(this.world,1.5,4,6,0xb48972,x,2,z);box(this.world,.03,1.5,1,0x314954,x+(x>0?-.8:.8),2.5,z);box(this.world,.03,1.65,1.15,0xdbb693,x+(x>0?-.81:.81),2.5,z-1.8);}this.target=new THREE.Group();this.world.add(this.target);const ring=mesh(new THREE.TorusGeometry(1,.055,8,64),material(0xf5d37f,{emissive:0xb49132,emissiveIntensity:.5}),this.target,0,.045,0);ring.rotation.x=Math.PI/2;mesh(new THREE.CylinderGeometry(.45,.45,.012,40),material(0x77634b),this.target,0,.014,0);this.ball=sphere(this.world,.15,0x5aced4,0,.2,5);this.ball.material.metalness=.55;this.ball.material.roughness=.13;this.aimLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xb5e9d0,transparent:true,opacity:.7}));this.world.add(this.aimLine);}
 if(stage===4){box(this.world,12,.3,11,0x323d51,0,-.18,5);box(this.world,12,.3,14,0x323d51,0,-.18,-47);for(const x of [-3.3,3.3]){box(this.world,.15,.25,43,0x727e95,x,-.4,-20);box(this.world,.05,.08,43,0x70d9c3,x,-.23,-20,{emissive:0x70d9c3,emissiveIntensity:1.3});}for(let row=0;row<8;row++)for(let side=0;side<2;side++){const safe=SAFE_GLASS[row]===side,x=side?1.65:-1.65,z=-3-row*5;const tile=box(this.world,2.7,.16,3.8,safe?0x8bcdc8:0xbba4ba,x,-.08,z,{transparent:true,opacity:.5,metalness:.3,roughness:.15});const cracks=new THREE.Group();cracks.position.set(x,.015,z);this.world.add(cracks);if(!safe){for(let i=0;i<3;i++){const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-.7+i*.4,0,-.8),new THREE.Vector3(-.2+i*.3,0,-.1),new THREE.Vector3(.6-i*.2,0,.75)]),new THREE.LineBasicMaterial({color:0xff9ea8,transparent:true,opacity:.6}));cracks.add(line);}}this.tiles.push({tile,cracks,key:`${row}:${side}`});box(this.world,2.8,.12,.1,0x8592a7,x,-.2,z-1.95);box(this.world,2.8,.12,.1,0x8592a7,x,-.2,z+1.95);}for(let z=-2;z>-44;z-=8){box(this.world,.1,8,.1,0x66748c,-3.3,-4,z);box(this.world,.1,8,.1,0x66748c,3.3,-4,z);}this.exit(-43);}
 if(stage===5){let start=10;for(const [a,b] of [...PITS].sort((a,b)=>b[1]-a[1])){this.floor((start+b)/2,start-b,22);start=a;}this.floor((start-57)/2,start+57,22);for(const o of HURDLES){box(this.world,o.w,.18,o.d,0xd8bc73,o.x,o.h,o.z);for(const x of [-7.5,7.5])box(this.world,.15,o.h,.15,0x877159,x,o.h/2,o.z);}for(const b of BEAMS){const beam=box(this.world,3.3,.45,.45,0xf55579,0,.8,b.z,{emissive:0xf55579,emissiveIntensity:.55});this.beams.push({mesh:beam,...b});box(this.world,18,.03,.04,0x673547,0,.03,b.z);}for(const [a,b] of PITS){box(this.world,22,.03,.1,0xf0bb64,0,.01,a);box(this.world,22,.03,.1,0xf0bb64,0,.01,b);}this.exit();}
 }
 setPlayers(players=[],ownId='') {this.remoteRoster=players;this.ownId=ownId;}
 updatePlayers(dt,now){
 const ids=new Set(this.remoteRoster.filter(p=>p.id!==this.ownId&&!p.eliminated).map(p=>p.id));
 for(const [id,p] of this.remoteActors)if(!ids.has(id)){p.rig.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});this.world.remove(p.rig);this.remoteActors.delete(id);}
 const colors=[0x176b60,0x3d6794,0xa27339,0x7860a5];
 this.remoteRoster.forEach((info,index)=>{if(!ids.has(info.id))return;let actor=this.remoteActors.get(info.id);if(!actor){actor=humanoid(this.world,{color:colors[index%4],number:String(456+index)});actor.tag=sign(actor.rig,info.name,0,2.35,0,1.35,'#ffffff','#172531');this.remoteActors.set(info.id,actor);const p=info.game.position;actor.rig.position.set(p.x,p.y,p.z);}
 const g=info.game,target=new THREE.Vector3(g.position.x,g.position.y,g.position.z);
 if(this.stage===1)target.set((index-(this.remoteRoster.length-1)/2)*1.2,0,3);
 if(this.stage===2)target.set(.9+index*.45,0,3+index*.5);
 if(this.stage===3)target.set((index-(this.remoteRoster.length-1)/2)*1.5,0,5);
 const moving=actor.rig.position.distanceTo(target)>.035;actor.rig.position.lerp(target,1-Math.exp(-dt*14));actor.animate(now,g.status==='playing'&&moving?1:0);actor.tag.quaternion.copy(this.camera.quaternion);
 });
 if(this.stage===0)for(const npc of this.npcs)npc.rig.visible=!this.remoteRoster.length;
 const ownIndex=this.remoteRoster.findIndex(p=>p.id===this.ownId),own=this.remoteRoster[ownIndex];this.player.setIdentity(colors[Math.max(0,ownIndex)],String(456+Math.max(0,ownIndex)));this.player.rig.visible=!own?.eliminated;
 }
 update(game,dt,now){if(this.stage!==game.stage)this.load(game.stage);const p=this.player,old=p.rig.position.clone();if([0,4,5].includes(game.stage)){p.rig.position.set(game.position.x,game.position.y,game.position.z);const moving=old.distanceTo(p.rig.position)>dt*.3;p.animate(now,moving?1:0);p.rig.rotation.z=THREE.MathUtils.damp(p.rig.rotation.z,game.grounded?0:.04,8,dt);}else p.animate(now,0);
 if(this.doll){this.doll.rig.rotation.y=THREE.MathUtils.damp(this.doll.rig.rotation.y,game.red?Math.PI:0,8,dt);for(let i=0;i<this.npcs.length;i++){const npc=this.npcs[i];if(game.status==='playing'&&!game.red){npc.rig.position.z=Math.max(-46,npc.rig.position.z-dt*(2.7+i%4*.4));npc.animate(now+i,1);}else npc.animate(now+i,0);}}
 if(game.stage===2){for(let i=0;i<this.npcs.length;i++){const n=this.npcs[i],friendly=i%2===0;n.rig.position.z=(friendly?4+Math.floor(i/4)*1.2:-8-Math.floor(i/4)*1.2)-(game.pull-.5)*3;n.rig.rotation.x=friendly?-.18:.18;n.arms.forEach(a=>a.rotation.x=friendly?-1.2:-1.2);n.legs.forEach((l,j)=>l.rotation.x=j?.3:-.3);}p.arms.forEach(a=>a.rotation.x=-1.2);p.rig.rotation.x=-.2;this.rope.position.z=-3-(game.pull-.5)*3;}
 if(this.target){this.target.position.set(game.targetX,0,-10);const end=marbleLanding(game.aim,game.charging?game.power:.79);this.aimLine.geometry.dispose();this.aimLine.geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,.1,5),new THREE.Vector3(end.x,.1,end.z)]);if(game.shot){const t=Math.min(1,game.shot.age/1.05);this.ball.position.set(game.shot.end.x*t,.2+Math.sin(t*Math.PI)*2.2,5+(game.shot.end.z-5)*t);}else this.ball.position.set(0,.2,5);p.arms[1].rotation.x=game.charging?-1:0;}
 for(const tile of this.tiles){const visible=!game.broken.has(tile.key);tile.tile.visible=visible;tile.cracks.visible=visible;}for(const b of this.beams)b.mesh.position.x=Math.sin(game.elapsed*b.speed+b.phase)*6;
 const target=new THREE.Vector3(),look=new THREE.Vector3();if(game.stage===1){target.set(5,5,7);look.set(0,1,0);}else if(game.stage===2){target.set(7,5,13);look.set(0,1,-4);}else if(game.stage===3){target.set(5,5.8,12);look.set(0,.5,-4);}else{const pos=p.rig.position;target.set(pos.x+2.4,Math.max(pos.y,0)+4.1,pos.z+7.6);look.set(pos.x*.7,Math.max(pos.y,0)+1,pos.z-8);}this.camera.position.lerp(target,1-Math.exp(-dt*4));this.camera.lookAt(look);this.updatePlayers(dt,now);this.composer.render();}
}
